// <auto-generated />
using System;
using DSR_N2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DSR_N2.Migrations
{
    [DbContext(typeof(DSR_N2Context))]
    [Migration("20200411000407_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DSR_N2.Models.Dobava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cena")
                        .HasColumnType("float");

                    b.Property<DateTime>("Datum_Nakupa")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KletId")
                        .HasColumnType("int");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int?>("VinoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KletId");

                    b.HasIndex("VinoId");

                    b.ToTable("Dobava");
                });

            modelBuilder.Entity("DSR_N2.Models.Klet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naslov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Klet");
                });

            modelBuilder.Entity("DSR_N2.Models.Proizvajalec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proizvajalec");
                });

            modelBuilder.Entity("DSR_N2.Models.Vino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alkohol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProizvajalecId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProizvajalecId");

                    b.ToTable("Vino");
                });

            modelBuilder.Entity("DSR_N2.Models.Dobava", b =>
                {
                    b.HasOne("DSR_N2.Models.Klet", "Klet")
                        .WithMany("Dobave")
                        .HasForeignKey("KletId");

                    b.HasOne("DSR_N2.Models.Vino", "Vino")
                        .WithMany("Dobave")
                        .HasForeignKey("VinoId");
                });

            modelBuilder.Entity("DSR_N2.Models.Vino", b =>
                {
                    b.HasOne("DSR_N2.Models.Proizvajalec", "Proizvajalec")
                        .WithMany("Vina")
                        .HasForeignKey("ProizvajalecId");
                });
#pragma warning restore 612, 618
        }
    }
}
